# Demo 3 - Programming Python Data Structures

#### Tuples
 - A tuple is a fixed-length immutable sequence of heterogeneous objects
 - Once initialized, tuple contents cannot be modified
 - Creating tuple using parentheses **()** is recommended for readability but not required
 - Access tuple elements using square brackets **[]** and zero-based index


In [3]:
tuple1 = (1, 2, 3)
tuple2 = 4, 5, 6

tuple3 = (42, 3.14, "Mick")
secret_of_life = tuple3[0]

secret_of_life

StatementMeta(, 84a7ca71-c29f-4bef-9f03-9b10f12aad29, 5, Finished, Available)

42

##### Tuple can be unpacked to multiple variables 

In [1]:
band_tuple = ("John", "Paul", "George", "Ringo")
# unpacking tuple into multiple variables
singer1, singer2, singer3, singer4 = band_tuple

singer3

StatementMeta(, c9c90949-1c09-4977-b599-46d44939bccd, 3, Finished, Available)

'George'

##### Unpacking tuple requires correct number of variables or error will occur

In [ ]:
band_tuple = ("John", "Paul", "George", "Ringo")

singer1, singer2 = band_tuple # ERROR: too many values to unpack 


#### Lists
 - List is variable-length, update-able sequence of heterogeneous objects
 - Use square brackets **[]** to create list and to access items using zero-based index
 - List object provides support for adding, updating and removing objects from list

In [1]:
my_list = [2, 4, 6, 8]

third_item = my_list[2]

band_list = [ "John", "Paul", "George", "Pete" ]

band_list.remove("Pete")     # remove exisitng item
band_list.append("Richard")  # add new item
band_list[3] = "Ringo"       # update existing item

band_list

StatementMeta(, 84a7ca71-c29f-4bef-9f03-9b10f12aad29, 3, Finished, Available)

['John', 'Paul', 'George', 'Ringo']

##### Lists support slicer **[ start : end ]** syntax similar to strings

In [2]:
list_of_years = [1960, 1964, 1968, 1972, 1976, 1980 ]

selected_years = list_of_years[3:5]

selected_years


StatementMeta(, 84a7ca71-c29f-4bef-9f03-9b10f12aad29, 4, Finished, Available)

[1972, 1976]

##### Simple List Enumeration

In [ ]:
favorite_languages = [ "C#", "Java", "TypeScript", "DAX", "M", "SQL", "Python" ]

for (index, value) in enumerate(favorite_languages):
    print(f"{index}:{value}")


#### Dictionaries
 - Dictionary is associative array of name-value pairs
 - Dictionary created using curly braces **{ }** with enclosed key-value pairs
 - Dictionary items accessible using square brackets **[ key ]** with enclosed key 


In [1]:
my_dictionary = { 
    "key1": "any arbitrary value", 
    "key2": 42, 
    "Key3": None
}

secret_of_life  = my_dictionary['key2']

secret_of_life

StatementMeta(, a38dd3d7-258e-49db-b4b6-6634a1ca081b, 3, Finished, Available)

42

###### Use **dictionary[ key ]** syntax to add or update items in dictionary

In [ ]:
# create empty dictionary
singer = {} 

# add new key-value pairs
singer["first_name"] = "John"
singer["last_name"] = "Mellencamp"

# update existing dictionary value 
singer["first_name"] = "Johny"
singer["last_name"] = "Cougar"

singer

##### Calling Functions By Passing Tuples and Dictionaries
 - Python allows passing function parameter list as tuple or as dictionary
 - Call function with tuple to pass positional parameters using * syntax
- Call function with dictionary to pass keyword parameters using ** syntax

In [ ]:
def broadcast_message(message, repeat=False):
    print(message)
    if(repeat):
        print('One more time - ' + message)

# call passing tuple with positional parameters using * syntax 
tupleParams = ('Hello from a tuple', True)
broadcast_message(*tupleParams)

# call passing disctionary with keyword parameters using ** syntax
dictParams = { 'message':'Hello from a dictionary', 'repeat': True }
broadcast_message(**dictParams)

#### Sets
 - Set is an unordered collection of unique elements
 - Create set using either curly braces **{}** or by passing list to **set()** function
 - Provides mathematical set operations like **union()**, **intersection()** and **difference()**



In [6]:
set1 = {2, 4, 6, 8}
set2 = set( [2, 4, 8, 16, 32, 32, 64] )

set_union = set1.union(set2)                 # Union = {2, 4, 6, 8, 16, 32, 64}
set_intersection = set1.intersection(set2)   # Intersection = {2, 4, 8}
set_difference = set1.difference(set2)       # Difference = {6}

set_difference

StatementMeta(, 4563a230-2a17-4201-9758-79e21699ab57, 8, Finished, Available)

{6}

#### NumPy Arrays
 - Numerical Python (NumPy) library provides high-performance **ndarray** array type
 - **ndarray** object is multi-dimensional array of homogeneous-type objects
 - Create **ndarray** object from list using NumPy **array()** function
 - **numpy** module renamed to **np** by convention

In [ ]:
import numpy as np

# create nd-array object from list of integers
my_array = np.array( [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ] )

print( my_array )         # [ 1  2  3  4  5  6  7  8  9 10]
print( my_array.size )    # 10
print( my_array.dtype )   # int64
print( my_array.max() )   # 10
print( my_array.mean() )  # 5.5


##### Create **ndarray** objects containing sequence of numbers using **np.arrange()**

In [22]:
import numpy as np

my_array1 = np.arange(4)        # array([0, 1, 2, 3])
my_array2 = np.arange(1, 5)     # array([1, 2, 3, 4])
my_array3 = np.arange(2, 9, 2)  # array([2, 4, 6, 8])

my_array3

StatementMeta(, 17bc0fe7-9531-42d0-828d-f7e84a9fbec0, 24, Finished, Available)

array([2, 4, 6, 8])

##### Create **ndarray** object containing numbers with linear spacing using **np.linspace()**

In [9]:
import numpy as np

np.linspace(1, 10, 24)


StatementMeta(, c3abbeb3-445f-461d-be99-c509f101f8d4, 11, Finished, Available)

array([ 1.        ,  1.39130435,  1.7826087 ,  2.17391304,  2.56521739,
        2.95652174,  3.34782609,  3.73913043,  4.13043478,  4.52173913,
        4.91304348,  5.30434783,  5.69565217,  6.08695652,  6.47826087,
        6.86956522,  7.26086957,  7.65217391,  8.04347826,  8.43478261,
        8.82608696,  9.2173913 ,  9.60869565, 10.        ])

#### Updating NumPy Arrays using Vectorized Operations
 - NumPy arrays support efficient write operations using vectorized computation
 - Vectorized operation used to perform mathematical updates on every item in array
 - Vectorized operation provides fast and easy way to update all array items without looping
 - Syntax for vectorized operation involves performing operation directory against array

In [8]:
import numpy as np

my_array1 = np.arange(4, 20, 4)   # array([ 4,  8, 12, 16])
my_array2 = np.square(my_array1)  # array([ 16,  64, 144, 256])
my_array3 = (my_array2 * 10)      # array([ 160,  640, 1440, 2560])

my_array3

StatementMeta(, 33b80d41-a9a9-4d32-aeba-9b404ff97dff, 10, Finished, Available)

array([ 160,  640, 1440, 2560])

##### NumPy arrays support broadcasting allowing mathematical operations between arrays
 - This simple example involves multiplying two arrays to create multiplication product array


In [3]:
import numpy as np

array1 = np.array( [1, 2, 3] )
array2 = np.array( [10, 20, 30] )

array3 = array1 * array2  # array([10, 40, 90])

array3

StatementMeta(, , , Waiting, )